name = 'twikoo-comments'
main = 'src/index.js'
compatibility_date = '2024-11-11'
[[vars]
ADMIN_KEY = "a358071315"
]
binding = 'DB'
database_name = 'twikoo-db'
database_id = 'e0b4f965-7be1-48ac-b800-9d05a9ab391a'

